spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    default-schema: public
    drop-first: false
    change-log: classpath:db/changelog/db.changelog.yaml
server:
  port: 8082


